version: '3'

services:

  php-server:
    build: .cloud/docker
    image: php7.3-fpm
    container_name: lemp_php-fpm
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached
    expose:
      - "9000"

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=lemp_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:1.15
    container_name: nginx115
    ports:
      - "80:80"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - .cloud/nginx/pma.conf:/etc/nginx/conf.d/pma.conf:cached
      - ./:/application:cached
    depends_on:
      - php-server

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lemp-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456789
      - PMA_ABSOLUTE_URI=http://phpmyadmin.localhost
    volumes:
      - .cloud/phpmyadmin/sessions:/sessions
    ports:
      - "8080:80"
    depends_on:
      - mysql

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 123456789
    ports:
      - "6379:6379"
